#
# Site settings
# ---------------------------
title: DevMarks
descriptions: this is a develop marks
name: DevMarks
email: supgeek.rod@gmail.com


#
# Build settings
# ---------------------------
markdown: redcarpet
markdown_ext: "html,md"
exclude: [ template-category-page.html ]
